# values.yaml
secrets:
  name: my-secrets

image:
  repository: jellyfin/jellyfin
  tag: latest@sha256:bc9fa8e1462fffe3d8d4255fc62af478602641f4c0e5f4875fea8563d1189837

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
