# values.yaml
secrets:
  name: my-secrets

image:
  repository: jellyfin/jellyfin
  tag: latest@sha256:1694ff069f0c9dafb283c36765175606866769f5d72f2ed56b6a0f1be922fc37

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
