apiVersion: apps/v1
kind: Deployment
metadata:
  name: godns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: godns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: godns
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: godns
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsGroup: {{ .Values.user.PGID }}
            runAsUser: {{ .Values.user.PUID }}
          volumeMounts:
            - mountPath: /config.json
              name: godns-cm0
              readOnly: true
              subPath: config.json
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: config.json
                path: config.json
            name: godns-cm0
          name: godns-cm0