# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/prowlarr
  tag: rolling@sha256:53b9cccebceab12825be1a22f2f9c2a2e8fa5e4c6a0aa78286fbe90a317fa070

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
