# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/prowlarr
  tag: rolling@sha256:8a140c9104c754a272f5e0d1dfcb32a06f07946a431a45c1083a16344f531748

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
