# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/prowlarr
  tag: rolling@sha256:13c576d2ad93764ab78d4e75c80447bc5489a06a15fd39e89c0be0be01e2ba3a

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
