# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/bazarr
  tag: rolling@sha256:17dc1cff22e99694ffbfb06555526cb47a66b362b4d6c982f06b557f7caae2bb

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
