# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/bazarr
  tag: rolling@sha256:e5d192a6f62a4f2336b40e1021fb3e31acfeb125ba970b65bcf6d607e29146cf

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
