# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/bazarr
  tag: rolling@sha256:80cb090162b47ea1bfb499d742b45a460b282f17ffefa4c01d518a5c8d52a5a4

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
