# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/cloudtube-ng
  tag: latest@sha256:0fba9988431529a60e24bf87e4f22dc40deeeaec2d411781641c8cda21ced443

env:
  TZ: Africa/Nairobi

user:
  PUID: 132
  PGID: 136
