# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/cloudtube
  tag: latest@sha256:cb9c4959f53d27b885991eb86e81062ed2c07e8f9e8bc9b6e619104858c9ce89

env:
  TZ: Africa/Nairobi

user:
  PUID: 132
  PGID: 136
