# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/cloudtube-ng
  tag: latest@sha256:27c544872ba946a5c939b3b197beecf30cc9eb1f92a9da976e47883b0c1f275c

env:
  TZ: Africa/Nairobi

user:
  PUID: 132
  PGID: 136
