apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quetre
  name: quetre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quetre
  template:
    metadata:
      labels:
        app: quetre
    spec:
      containers:
        - env:
            - name: REDIS_URL
              value: {{ .Values.valkey.SERVICE }}:6379
            - name: TZ
              value: "{{ .Values.env.TZ }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: quora
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: quetre
spec:
  selector:
    app: quetre
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000