# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/wikiless
  tag: latest@sha256:68d3f56d9eaf440e748588ea0ecfe95847ac0efc76e1cf166f00e7f9f8828e57

env:
  TZ: Africa/Nairobi

valkey:
  SERVICE: valkey
