# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/wikiless
  pinned: sha256:5e8af4b46a48e21c44b49b6da62f26fa786b10136ff0b8819cbf7248ca624e09

env:
  TZ: Africa/Nairobi

valkey:
  SERVICE: valkey
