# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/wikiless
  tag: latest@sha256:7ed7dc49a0056b00a928ae567ab448fb5686754994d5ad81ca03133f3dcabccc

env:
  TZ: Africa/Nairobi

valkey:
  SERVICE: valkey
