# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/radarr
  tag: rolling@sha256:09979c77f9be3f324c133e1e73fea2b5c7eed37b586ed7c8a8a60c9b6932f175

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
