# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/radarr
  tag: rolling@sha256:846f8574f2745d9f713981dd6dea3041cab27110b5517f30b533252283d6d25d

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
