# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/radarr
  tag: rolling@sha256:01ab4edc881b117e30972482ae4362c13ca76ee73c891a7581cffe597d43ca31

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
