# values.yaml
image:
  repository: ghcr.io/germondai/trawl
  pinned: 1.8.0@sha256:44091fc0af5f9a0190d4cb23d944f69207684a28382a921800dda5b73b41ba2f

env:
  TZ: Africa/Nairobi

valkey:
  SERVICE: valkey

user:
  PUID: 123
  PGID: 118