# values.yaml
secrets:
  name: my-secrets

image:
  repository: lscr.io/linuxserver/nextcloud
  tag: latest@sha256:ef955d3b2faf91bad4b3e83e9325a8e1652727136007567e46f17856a57b0727

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001