# values.yaml
secrets:
  name: my-secrets

image:
  repository: lscr.io/linuxserver/nextcloud
  tag: latest@sha256:26fef2e985cdec2178506babaed036eeb76764e500b79ecd306c96cd65f9bf84

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001