# values.yaml
secrets:
  name: my-secrets

image:
  repository: miniflux/miniflux
  tag: 2.3.0-distroless@sha256:3a95fd1f9f75eb55b880004aee4084bb94ad60d8349de302e0b86f8620612311

postgresImage:
  repository: postgres
  tag: 18-alpine

user:
  PUID: 1001
  PGID: 1001