# values.yaml
secrets:
  name: my-secrets

image:
  repository: quay.io/invidious/invidious
  tag: master-arm64@sha256:541cdc82071c4a7d2147e1afcb1ed2d7cb2b64ef64c94f1ba4b507b3dc111db5

postgresImage:
  repository: postgres
  tag: 15-alpine

user:
  PUID: 133
  PGID: 137
