# values.yaml
secrets:
  name: my-secrets

image:
  repository: quay.io/invidious/invidious
  tag: master-arm64@sha256:769b874b3cc6e76a4b9836c965f982a4a9d8194d07f3d2c2b0052ac92bd07fb0

postgresImage:
  repository: postgres
  tag: 15-alpine

user:
  PUID: 133
  PGID: 137
