# values.yaml
secrets:
  name: my-secrets

image:
  repository: quay.io/invidious/invidious
  tag: master-arm64@sha256:4d5db4b26e8238b7de5814c9d2f00613dc2277e0872f0b0972f182cd738984a8

postgresImage:
  repository: postgres
  tag: 15-alpine

user:
  PUID: 133
  PGID: 137
