# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/sonarr
  tag: rolling@sha256:83607d2b741ec9469db09489e88c473ae6fdf7d85f3b55d4fa809b43e25a2a6c

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
