# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/sonarr
  tag: rolling@sha256:e679d9abf64f7a1edaf340f5c3fea20efed55fb1489ef8ba42f3404caed43590

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
