# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/sonarr
  tag: rolling@sha256:6806001ccc2ec95d941c9c0de012dbcb59c6a33932cfc17f71e300bdd48cabfe

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
