name: Renovate

on:
#  schedule:
#    - cron: "0 0 * * *"  # runs every day at 00:00 UTC
  workflow_dispatch:
  push:
#  pull_request:
#    types:
#      - opened
#      - synchronize
#      - reopened

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Renovate
        uses: renovatebot/github-action@v40.3.4
        with:
          # You can customize Renovate configuration here if needed
          # For example, to specify the configuration file path:
        #  config-file: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
