# values.yaml
secrets:
  name: my-secrets

image:
  repository: lscr.io/linuxserver/jackett
  tag: latest@sha256:a5ec860123a5c46c64f6dfd5514b9a2c59e0f0157872515b6b17f8b38372db

env:
  TZ: Africa/Nairobi

user:
  PUID: 131
  PGID: 135
